[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_solana_dapp = "89xQFfYcAGqoYHJZa93gSTZLxY5wSwxSf94cWeXVcbbj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8898"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
